# Generated by Django 2.2.4 on 2019-09-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=250)),
                ('massage', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
