# Generated by Django 2.2.4 on 2019-09-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='massage',
            field=models.CharField(max_length=1050),
        ),
    ]
