# Generated by Django 2.2.4 on 2019-09-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_auto_20190903_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner1', models.ImageField(upload_to='bennne')),
                ('banner2', models.ImageField(upload_to='bennne')),
                ('banner3', models.ImageField(upload_to='bennne')),
                ('banner4', models.ImageField(upload_to='bennne')),
                ('banner5', models.ImageField(upload_to='bennne')),
            ],
        ),
    ]
