# Generated by Django 2.2.4 on 2019-09-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='photfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popupimg', models.ImageField(upload_to='')),
                ('photimg', models.ImageField(upload_to='')),
                ('item', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
