# Generated by Django 2.2.4 on 2019-09-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190904_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photfolio',
            name='photimg',
        ),
    ]
